# Generated by Django 4.1 on 2022-08-20 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_seller', '0002_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.IntegerField()),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_seller.products')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_seller.user_seller')),
            ],
        ),
    ]
