# Generated by Django 4.1 on 2022-08-20 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_seller', '0003_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='orderid',
        ),
    ]
