# Generated by Django 4.1 on 2022-08-21 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_seller', '0004_remove_cart_orderid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
